worker_processes 1;
events { 
    worker_connections 1024; 
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 443 ssl;
        server_name deletebadzim.aurorass.art;

        ssl_certificate /etc/letsencrypt/live/deletebadzim.aurorass.art/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/deletebadzim.aurorass.art/privkey.pem;

        # Отдаём статические файлы
        location /static/ {
            alias /usr/share/nginx/html/static/;
        }

        # Все остальные запросы — web.html (SPA)
        location / {
            try_files $uri $uri/ /static/web.html;
        }
    }

    server {
        listen 80;
        server_name deletebadzim.aurorass.art;
        return 301 https://$host$request_uri;
    }
}